# Generated by Django 3.2 on 2021-05-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_Cream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='')),
                ('price', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('inventory', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
