# Generated by Django 3.2 on 2021-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice_cream',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='ice_cream',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
