# Generated by Django 3.2 on 2021-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210516_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=0, max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
                ('address', models.TextField(max_length=2000)),
            ],
        ),
    ]
