# Generated by Django 3.2 on 2021-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
