# Generated by Django 3.2 on 2021-05-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
