# Generated by Django 3.2 on 2021-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ice_cream_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='images',
            field=models.BinaryField(),
        ),
    ]
