# Generated by Django 3.2 on 2021-05-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_ice_cream_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
