# Generated by Django 3.2 on 2021-05-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentS',
        ),
    ]
