# Generated by Django 3.2 on 2021-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice_cream',
            name='categories',
            field=models.CharField(choices=[('N', 'Normal'), ('G', 'Good'), ('D', 'Delicious')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ice_cream',
            name='frequencies',
            field=models.CharField(choices=[('F', 'Favorite'), ('N', 'Not Favorite')], default='', max_length=100),
        ),
    ]
