# Generated by Django 3.2 on 2021-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210608_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_cream',
            name='frequencies',
            field=models.CharField(choices=[('F', 'Favorite'), ('L', 'Little')], default='', max_length=100),
        ),
    ]
