# Generated by Django 3.2 on 2021-06-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='items',
            field=models.ManyToManyField(related_name='statistics', to='order.Ice_Cream'),
        ),
    ]
