# Generated by Django 3.2 on 2021-06-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_statistics_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='items',
        ),
    ]
